apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-dotnet-app
spec:
  selector:
    matchLabels:
      app: mes-dotnet-app
  template:
    metadata:
      labels:
        app: mes-dotnet-app
        system: mes-system
    spec:
      containers:
      - name: mes-dotnet-app
        image: mes-poc-dotnet-app
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mes-system-env
        - secretRef:
            name: mes-system-secrets
          