apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: mes-dotnet-app
spec:
  parentRefs:
  - name: mes-gateway
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /weatherforecast
      method: GET
    backendRefs:
    - name: mes-dotnet-app-svc
      port: 80